### ISSUE TITLE
Doesn't work on macOS 

### ISSUE THREAD

**Issue by rogaha** [paulovcmedeiros/pyRobBot#5]
**Describe the bug**

<img width="1471" alt="Screenshot of Safari at May 21, 2024 at 5_24_49 PM" src="https://github.com/paulovcmedeiros/pyRobBot/assets/4483394/520cbc78-738b-465a-97f3-01d5d5415090">

```

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://192.168.1.215:8502

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog

2024-05-21 17:20:42.020 Uncaught app exception
Traceback (most recent call last):
  File "/Users/rogaha/development/nextron/ai-agents/auto-gen/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/Users/rogaha/development/nextron/ai-agents/auto-gen/lib/python3.11/site-packages/pyrobbot/app/app.py", line 17, in <module>
    run_app()
  File "/Users/rogaha/development/nextron/ai-agents/auto-gen/lib/python3.11/site-packages/pyrobbot/app/app.py", line 13, in run_app
    ).render()
      ^^^^^^^^
  File "/Users/rogaha/development/nextron/ai-agents/auto-gen/lib/python3.11/site-packages/pyrobbot/app/multipage.py", line 708, in render
    return super().render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rogaha/development/nextron/ai-agents/auto-gen/lib/python3.11/site-packages/pyrobbot/app/multipage.py", line 465, in render
    self.handle_ui_page_selection(**kwargs)
  File "/Users/rogaha/development/nextron/ai-agents/auto-gen/lib/python3.11/site-packages/pyrobbot/app/multipage.py", line 602, in handle_ui_page_selection
    new_configs = self.selected_page.chat_obj.configs.model_validate(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rogaha/development/nextron/ai-agents/auto-gen/lib/python3.11/site-packages/pydantic/main.py", line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for VoiceChatConfigs
ai_instructions
  Input should be a valid tuple [type=tuple_type, input_value="('You answer correctly.'...citly asked to do so.')", input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/tuple_type
```

**To Reproduce**
1. `pip uninstall git+https://github.com/paulovcmedeiros/pyRobBot.git`
2. run: `rob`

**Expected behavior**
Open the streamlit application locally. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by All-Ki** [comment]
Same on windows 11
